# -*- coding: utf-8 -*-
"""ML linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eA7wDCjmpq28uIRABsXWu540s-USZ0dg
"""

import pandas as pd

dataset=pd.read_csv("/content/salary dataset.csv")

dataset

x=dataset[["Experience (Years)"]]
y=dataset[["Salary (₹)"]]

from sklearn.model_selection import train_test_split

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
# test and train,split it and fix a test size as a 20% its a better for testing and random size is shuffle the dataset in any row to row.

from sklearn.linear_model import LinearRegression

#Train the Linear Regression model
reg=LinearRegression()
reg.fit(X_train,y_train) #training the model use of x_train,y_train to using it

# Predict
y_pred = reg.predict(X_test)
y_pred# trained to be tested so use predict

#checking model accuracy so we used r2 score
from sklearn.metrics import r2_score

r2 = r2_score(y_test,y_pred)
print("R² Score:", r2) # use r2 score to find out the accuracy of model,if it is above 92 to 95 its a good.

# --- Save model ---
import pickle
pickle.dump(reg, open('model.sav', 'wb'))# import the pickle and using a model to open and write binary to it

loaded_model  = pickle.load(open('model.sav', 'rb')) # load the saved model and read binary to next x_test to predict it
predictions = loaded_model.predict([[20]])
print(predictions)